### PR TITLE
Add a few more examples

### PR DESCRIPTION
**Pull request by green-big-frog**
I added some examples that are useful on almost any bot.

### CODE REVIEW

**Comment by meew0** [comment]
Can you rename the "improved_ping.rb" to something like "ping_with_time.rb"? It's not really "improved", just does something different

**Comment by green-big-frog** [comment]
Do you also want me to fix the rubocop "errors"?

**Comment by meew0** [comment]
Yes, that would be perfect.

**Comment by green-big-frog** [comment]
I fixed all issues besides the warning that `eval` is a security risk.

**Comment by meew0** [comment]
Can you maybe make Rubocop ignore the eval lint in the examples folder? Put this at the end of the .rubocop.yml file:

```yml
Lint/Eval:
  Exclude:
    - examples/*
```

**Comment by green-big-frog** [comment]
I'd like to let you do the merging.

**Pull request merged**
