### PR TITLE
Invalid Channel/User/Server ID returns nil

### PR DESCRIPTION
**Pull request by SnazzyPine25**

### CODE REVIEW

**Comment by SnazzyPine25** [comment]
#116

**Comment by meew0** [comment]
Can you make it rescue only the specific error that occurs? Otherwise it'll return nil when anything else happens (say, no network connection, or invalid token)

**Comment by SnazzyPine25** [comment]
How could I do that exactly?

**Comment by meew0** [comment]
Find out what error the method raises when called with an invalid ID, then update the rescue statement with only that error

**Comment by SnazzyPine25** [comment]
`rescue 404`?

**Comment by meew0** [comment]
No, it will raise `RestClient::Something`, which is what you should rescue

**Comment by SnazzyPine25** [comment]
Alright.

**Pull request merged**
