### PR TITLE
Update concept of "default channel" per API change

### PR DESCRIPTION
**Pull request by z64**
Discord has (pending deployment at time of writing this PR) updated their API to remove the previous concept of the "default channel" being the channel with the same snowflake ID as the guild. It is now described as:

> ".. the channel with the highest position that their (the client) allows them to see (read)".

This API change also allows "default channels" to be deleted and hidden just like any other channel.

https://github.com/hammerandchisel/discord-api-docs/pull/329

### CODE REVIEW

**Comment by z64** [comment]
Woops this isn't quite right. Have to rework to scan channel's permission overwrites for @-everyone.

**Comment by z64** [comment]
This looks like it works properly.

**Comment by z64** [comment]
Squashed my fixup - this change is now fully live.

**Comment by LikeLakers2** [comment]
I know that this is a closed PR now, but because of the API change, it's now possible to have *no* channels whatsoever in a server. While there's little point to having a completely blank server, and even less point to having a bot join one, I'd like to ask that it be made sure that Discordrb can cope with a lack of channels in a server.

**Comment by meew0** [comment]
I tested it a bit and noticed no problems, so it should be fine.

**Pull request merged**
