### PR TITLE
Updated the #prune Channel method to make use of bulk_delete

### PR DESCRIPTION
**Pull request by snapcase**
Updated to make use of bulk_delete

https://github.com/hammerandchisel/discord-api-docs/blob/master/docs/resources/CHANNEL.md#bulk-delete-messages--post-channelschanneliddocs_channelchannel-objectsmessagesbulk_delete

### CODE REVIEW

**Comment by meew0** [comment]
Looks good, will test later

**Comment by hlaaftana** [comment]
if it's over 100, you could loop over the multiples of 100 by the amount of  messages and wait 1 second in between to very easily avoid the 1/1 ratelimit

**Comment by meew0** [comment]
Maybe, but it seems kinda pointless because you can just loop the call to `prune` (it gets new history every time)

**Comment by meew0** [comment]
Apparently, bulk deleting one message won't work either, can you change the lower limit to 2? (Thanks @DinosParkour)

**Pull request merged**
