### PR TITLE
Fix logger when token is an empty string

### LINKED ISSUE #448: Logger is broken if token is set to an empty string
1. Set token to `''`
2. `bot.run`
```
[ERROR : websocket @ 2018-01-17 11:53:00.617] REDACTED_TOKENTREDACTED_TOKENhREDACTED_TOKENeREDACTED_TOKEN REDACTED_TOKENwREDACTED_TOKENeREDACTED_TOKENbREDACTED_TOKENsREDACTED_TOKENoREDACTED_TOKENcREDACTED_TOKENkREDACTED_TOKENeREDACTED_TOKENtREDACTED_TOKEN REDACTED_TOKENcREDACTED_TOKENoREDACTED_TOKENnREDACTED_TOKENnREDACTED_TOKENeREDACTED_TOKENcREDACTED_TOKENtREDACTED_TOKENiREDACTED_TOKENoREDACTED_TOKENnREDACTED_TOKEN REDACTED_TOKENhREDACTED_TOKENaREDACTED_TOKENsREDACTED_TOKEN REDACTED_TOKENcREDACTED_TOKENlREDACTED_TOKENoREDACTED_TOKENsREDACTED_TOKENeREDACTED_TOKENdREDACTED_TOKEN:REDACTED_TOKEN REDACTED_TOKENnREDACTED_TOKENiREDACTED_TOKENlREDACTED_TOKEN
```

### PR DESCRIPTION
**Pull request by Daniel-Worrall**
Fixes #448

### CODE REVIEW

**Comment by z64** [comment]
Please change the commit message.

**Comment by Daniel-Worrall** [comment]
Please suggest a better commit message.

**Comment by LikeLakers2** [comment]
Your commit message is dumb. So how about this: `Don't redact token if there is no token set`

**Comment by Daniel-Worrall** [comment]
That would violate our commit style by not using the imperative present tense.

**Pull request merged**
