### PR TITLE
[CI] Test against Ruby 2.3, 2.4 and 2.5

### PR DESCRIPTION
**Pull request by nicolasleger**

### CODE REVIEW

**Comment by ChallahuAkbar** [comment]
Since you opened this PR literally an hour before I was about to, I figured I'd at least contribute and say that I'm pretty sure that we don't need that install bundler line anymore, and if we do, it should be using the latest version as well.

**Comment by ChallahuAkbar** [comment]
Just tested, and [yes](https://travis-ci.org/ChallahuAkbar/discordrb/jobs/361968250#L462), Travis uses the latest bundler already.

**Comment by nicolasleger** [comment]
Thanks, PR updated.

**Comment by z64** [comment]
Thanks!

**Pull request merged**
