### PR TITLE
Make embed a symbol in Channel#send_message

### PR DESCRIPTION
**Pull request by greenbigfrog**

### CODE REVIEW

**Comment by greenbigfrog** [comment]
I shouldn't PR past midnight

**Comment by LikeLakers2** [comment]
I was gonna say, what's wrong with this PR? Making it a symbol seems perfectly reasonable to me, I'm curious why you closed this.

**Comment by z64** [comment]
This was done as a follow up to a conversation in the channel about making *tts* a named argument, or at least moving it to the end of the arg, because no one uses TTS and it just makes the method call ugly.

Gbf however thought we were talking about making `embed` named, hence his comment and closing.

This also breaks bots.

**Comment by LikeLakers2** [comment]
Understood. I understand it can break bots, but I'd be in support of this even if it's kept on hold for a major update.

**Pull request closed without merging**
