### PR TITLE
Fix README to reflect proper testing procedures

### PR DESCRIPTION
**Pull request by kirillian**
There are no tests in this repository (yet). I recommend you remove the text trying to tell people how to run them until the tests are present.

### CODE REVIEW

**Comment by kirillian** [comment]
I'm sorry. I totally missed that spec folder. The rake false command fails as there is no rake task with the name 'false' (rake -T to see) and a quick inspection of the Rakefile confirms that. However, after looking again, it appears you are using rspec and rubocop without including the necessary dependencies in the Gemfile. I'll see if I can't get those working and make this PR reflect those changes instead.

**Comment by kirillian** [comment]
Meant to post that comment earlier but posted it on the wrong PR.

**Comment by kirillian** [comment]
You should now have a README that better reflects the commands necessary to run tests and the testing dependencies are now added to your gemspec file.

**Comment by meew0** [comment]
Yeah, I added some tests once but never finished integrating them into the installation procedure, thanks for that

**Pull request merged**
