### PR TITLE
Server Muting/Deafening

### PR DESCRIPTION
**Pull request by SnazzyPine25**

### CODE REVIEW

**Comment by meew0** [comment]
There seems to be something wrong with this PR - when I try to merge it over the git command line, it doesn't actually have the changes made (and they don't show up when viewing your fork over GitHub either). Could you recreate the changes on a separate branch based on my current master and then reopen the PR?

**Comment by SnazzyPine25** [comment]
Alright, I will do that later

**Comment by SnazzyPine25** [comment]
Ok weird, when I opened a new pr, it said it has no changes

**Comment by meew0** [comment]
Yeah, something in your repo is messed up, I'd advise you to make a new branch on your fork starting from https://github.com/meew0/discordrb/commit/5e2b892b4a82825397f01dc4e608cefe004a3903 (current HEAD of my repo) and copy-pasting over the changes

**Comment by SnazzyPine25** [comment]
Is there anyway to make a branch from a commit

**Comment by meew0** [comment]
`git checkout -b [name of branch] [commit SHA]`

**Comment by SnazzyPine25** [comment]
`fatal: reference is not a tree: 5e2b892b4a82825397f01dc4e608cefe004a3903`?

**Comment by meew0** [comment]
Are you sure you have the commit in your fork? Try creating a remote `upstream` that points to *my* repo and then `git fetch`ing it, then trying again.

**Pull request closed without merging**
