### PR TITLE
Playing Event Streaming Support

### PR DESCRIPTION
**Pull request by barkerja**
Adds support for (the not yet documented) `type` and `url` in the presence payload. This indicates if a member is streaming (`type` indicating which service: 0 no stream, 1 twitch; and a `url` provided to the location of the stream).

### CODE REVIEW

**Comment by meew0** [comment]
From a quick look, this seems to be a duplicate of #128. I'll take a more thorough look later, maybe there is something in your PR that the other doesn't

**Comment by barkerja** [comment]
> From a quick look, this seems to be a duplicate of #128. I'll take a more thorough look later, maybe there is something in your PR that the other doesn't

Oops, missed that one! After taking a quick look at #128, their PR appears to only update the type/url on Discord but doesn't provide a way to access that data through discordrb in any way when received by Discord.

Maybe we merge the two PRs?

**Comment by meew0** [comment]
Seems good, I'll take care of that when I review and merge all the PRs (either today or tomorrow)

**Comment by SnazzyPine25** [comment]
Nice!

**Comment by SnazzyPine25** [comment]
@barkerja can you also add `:streaming` to status?

**Comment by meew0** [comment]
Streaming is not a separate status though - a user can both be streaming and `:online` and streaming and `:idle`.

**Pull request merged**
